spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&autoReconnect=true&useSSL=true
    url: jdbc:mysql://localhost:3306/openlayer?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
#      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  type-aliases-package: com.nice.demo.bean
  mapper-locations: mapper/*.xml

devtools:
  livereload:
    enabled:true
    port:35729
  restart:
    enabled:true